/**
 * Viem-generated chain registry (mainnet and testnet).
 * Generated by: pnpm run generate-chains
 * Source: data/chains/mainnet.chains.json, data/chains/testnet.chains.json
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface RegistryChain {
  id: number;
  name: string;
  network?: string;
  rpcs: string[];
  explorer?: { name?: string; url?: string; apiUrl?: string };
  testnet: boolean;
}

let mainnetCache: RegistryChain[] | null = null;
let testnetCache: RegistryChain[] | null = null;

function getChainsDir(): string {
  const cwd = process.cwd();
  return join(cwd, "data", "chains");
}

function loadJson<T>(filePath: string): T {
  try {
    const raw = readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as T;
  } catch {
    return [] as unknown as T;
  }
}

export function getMainnetRegistry(): RegistryChain[] {
  if (mainnetCache) return mainnetCache;
  const dir = getChainsDir();
  mainnetCache = loadJson<RegistryChain[]>(join(dir, "mainnet.chains.json"));
  return mainnetCache;
}

export function getTestnetRegistry(): RegistryChain[] {
  if (testnetCache) return testnetCache;
  const dir = getChainsDir();
  testnetCache = loadJson<RegistryChain[]>(join(dir, "testnet.chains.json"));
  return testnetCache;
}

export function getRegistryChainById(chainId: string, testnet: boolean): RegistryChain | undefined {
  const registry = testnet ? getTestnetRegistry() : getMainnetRegistry();
  const id = parseInt(chainId, 10);
  if (Number.isNaN(id)) return undefined;
  return registry.find((c) => c.id === id);
}
